name: VSCODETOr
on:
  workflow_dispatch:
    inputs:
      USER_NAME:
        description: 'Enter USER NAME'
        required: true
      USER_PWD:
        description: 'Enter USER PWD'
        required: true
      ROOT_PWD:
        description: 'Enter ROOT PWD'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update OS
        run: sudo apt-get update -y && sudo apt-get upgrade -y > /dev/null 2>&1 && sudo apt-get -y install wget curl nano git xz-utils openssh-server build-essential net-tools dialog apt-utils libevent* libsecret* > /dev/null 2>&1
      - name: Install VSCODe
        run: |
          wget https://github.com/coder/code-server/releases/download/v4.9.1/code-server_4.9.1_amd64.deb
          sudo dpkg -i code-server_4.9.1_amd64.deb
      - name: Install TOr
        run: |
          wget https://deb.torproject.org/torproject.org/pool/main/t/tor/tor_0.4.7.13-1~jammy+1_amd64.deb
          sudo dpkg -i tor_0.4.7.13-1~jammy+1_amd64.deb
          sudo sed -i 's\#SocksPort 9050\SocksPort 9052\ ' /etc/tor/torrc
          sudo sed -i 's\#ControlPort 9051\ControlPort 9053\ ' /etc/tor/torrc
          sudo sed -i 's\#HashedControlPassword\HashedControlPassword\ ' /etc/tor/torrc
          sudo sed -i 's\#CookieAuthentication 1\CookieAuthentication 1\ ' /etc/tor/torrc
          sudo sed -i 's\#HiddenServiceDir /var/lib/tor/hidden_service/\HiddenServiceDir /var/lib/tor/hidden_service/\ ' /etc/tor/torrc
          sudo sed -i '72s\#HiddenServicePort 80 127.0.0.1:80\HiddenServicePort 12345 127.0.0.1:12345\ ' /etc/tor/torrc
          sudo sed -i '73s\#HiddenServicePort 22 127.0.0.1:22\HiddenServicePort 22 127.0.0.1:22\ ' /etc/tor/torrc
          sudo sed -i '74 i HiddenServicePort 8080 127.0.0.1:8080' /etc/tor/torrc
          sudo sed -i '75 i HiddenServicePort 4000 127.0.0.1:4000' /etc/tor/torrc
          sudo sed -i '76 i HiddenServicePort 8000 127.0.0.1:8000' /etc/tor/torrc
          sudo sed -i '77 i HiddenServicePort 9000 127.0.0.1:9000' /etc/tor/torrc
      - name: Add USER
        run: |
          sudo useradd -m ${{ github.event.inputs.USER_NAME }}
          sudo adduser ${{ github.event.inputs.USER_NAME }} sudo
          sudo echo '${{ github.event.inputs.USER_NAME }}:${{ github.event.inputs.USER_PWD }}' | sudo chpasswd
          sudo echo root:${{ github.event.inputs.ROOT_PWD }}| chpasswd
          sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd 
          sudo usermod -aG sudo ${{ github.event.inputs.USER_NAME }}
      - name: Run VSCODETOr
        run: |
          sudo tor >> tor.log &
          sudo code-server --bind-addr 127.0.0.1:12345 >> vscode.log &
          sleep 1m
          sudo cat /var/lib/tor/hidden_service/hostname
          sudo sed -n '3'p ~/.config/code-server/config.yaml
      - name: Loop
        run: |
          sleep 1m
          echo '######### OK #########'
          sleep 10m
          echo '######### OK #########'
          sleep 100m
          echo '######### OK #########'
          sleep 1000m
          echo '######### OK #########'
          sleep 10000m
          echo '######### OK #########'
          sleep 100000m
          echo '######### OK #########'
          sleep 1000000m
          echo '######### OK #########'
